// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD445392PibNJhyus8eRicg1laafnCzRuQ',
    appId: '1:404767129554:web:cd24a063385d22adc4120b',
    messagingSenderId: '404767129554',
    projectId: 'flutter-starter-dfcdc',
    authDomain: 'flutter-starter-dfcdc.firebaseapp.com',
    storageBucket: 'flutter-starter-dfcdc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZXDiyPImXwPiocJ1joqrMwMWpRwvjEc',
    appId: '1:404767129554:android:04f5d2002b3fd3b5c4120b',
    messagingSenderId: '404767129554',
    projectId: 'flutter-starter-dfcdc',
    storageBucket: 'flutter-starter-dfcdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5vQEjVrmzpnrWfdNnK-5BMp1tBrmRcYc',
    appId: '1:404767129554:ios:2be47dc9b5351994c4120b',
    messagingSenderId: '404767129554',
    projectId: 'flutter-starter-dfcdc',
    storageBucket: 'flutter-starter-dfcdc.appspot.com',
    iosClientId: '404767129554-4vv5v1apcb1v1hblr99744bqkqkvn08b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystoreStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5vQEjVrmzpnrWfdNnK-5BMp1tBrmRcYc',
    appId: '1:404767129554:ios:2be47dc9b5351994c4120b',
    messagingSenderId: '404767129554',
    projectId: 'flutter-starter-dfcdc',
    storageBucket: 'flutter-starter-dfcdc.appspot.com',
    iosClientId: '404767129554-4vv5v1apcb1v1hblr99744bqkqkvn08b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mystoreStarter',
  );
}
